In [4]:
import numpy as np

height = np.array([170, 165, 174, 169, 155, 172, 166, 168])
weight = np.array([60, 55, 75, 67, 49, 63, 58, 61])
GPA = np.array([4.1, 3.0, 2.8, 2.9, 3.1, 3.6, 3.7, 4.0])

# Calculate the mean vector
mean_vector = np.mean(np.array([height, weight, GPA]), axis=1)

# Calculate the covariance matrix
covariance_matrix = np.cov(np.array([height, weight, GPA]))

print("Mean Vector:")
print(mean_vector)

print("Covariance Matrix:")
print(covariance_matrix)

Mean Vector:
[167.375  61.      3.4  ]
Covariance Matrix:
[[33.69642857 39.42857143  0.37142857]
 [39.42857143 60.85714286 -0.94285714]
 [ 0.37142857 -0.94285714  0.26285714]]
